# Generated by Django 5.2.17 on 2026-09-03 07:40

import patients.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='raw_payload',
            field=patients.encryption.EncryptedJSONField(),
        ),
    ]
